### ISSUE TITLE
Importlab running under Python 3.6 and analyzing Python 2.7 can't find networkx

### ISSUE THREAD

**Issue by rchen152** [google/importlab#11]
Steps I took:

sudo apt-get install python-pip
pip install networkx  # puts networkx in ~/.local/lib/python2.7/site-packages/
virtualenv --python=python3.6 .venv3
source .venv3/bin/activate
pip install importlab
echo "import networkx" > foo.py
importlab -V2.7 foo.py --tree

`foo.py` shows up as the only file in the tree. On the other hand, if I install importlab under Python 2.7 and analyze Python 3.5 code (I didn't try 3.6 because pip3 is 3.5 on my machine), the last command (correctly) causes a bunch of networkx files to be printed as part of the tree.

**Comment by martindemello** [comment]
oddly enough `importlab -V 2.7 --unresolved foo.py` does not list networkx

**Comment by martindemello** [comment]
the import finder returns `/usr/local/google/home/mdemello/.local/lib/python2.7/site-packages/networkx` as the path to dep, and importlab should see that it is a directory and append `__init__.py` but it currently doesn't do that for system-resolved dependencies.

**Comment by martindemello** [comment]
further issue: from foo import bar tries both foo.bar and foo, and seems to be prematurely falling back to foo when foo.bar is a system path in this particular setup
