### ISSUE TITLE
use strongly connected component detection in the graph builder

### ISSUE THREAD

**Issue by martindemello** [google/importlab#34]
[Kosaraju's algorithm](https://en.wikipedia.org/wiki/Kosaraju's_algorithm) is already [implemented in networkx](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.components.kosaraju_strongly_connected_components.html), which could potentially simplify the cycle extraction code a lot.

**Comment by rchen152** [comment]
@xunyang01 expressed interest in working on this.

**Comment by rchen152** [comment]
Fixed by https://github.com/google/importlab/pull/39
